add auto-rollback phase to all e2e tests; add rollback state; keep last-error when rolling back; check state and last-error in test

diff --git a/.pipelines/templates/stages/testing_common/e2e-test-run.yml b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
--- a/.pipelines/templates/stages/testing_common/e2e-test-run.yml
+++ b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
@@ -137,11 +137,6 @@ steps:
         PROXY_ARG="--proxy HTTPS_PROXY=${{ parameters.httpsProxy }}"
       fi
 
-      FORCED_ROLLBACK_ARG=""
-      if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
-        FORCED_ROLLBACK_ARG="--forced-rollback"
-      fi
-
       echo "Running script to stage and finalize A/B update..."
       ./bin/storm-trident helper ab-update \
           "${{ parameters.sshKeyPath }}" \
@@ -152,7 +147,6 @@ steps:
           --version $(version) \
           --stage-ab-update \
           --finalize-ab-update \
-          $FORCED_ROLLBACK_ARG \
           $PROXY_ARG
 
       current_version=$(echo $(version))
@@ -166,14 +160,14 @@ steps:
     displayName: "🅱️🔄 Stage and finalize A/B update into target OS B"
     condition: and(succeeded(), ne(variables['abActiveVolume'], 'null'))
 
-  - bash: |
-      set -eu
-      if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
-        # auto-rollback will fail the first update (to volume-b) and
-        # the rollback should boot to volume-a
-        echo "##vso[task.setvariable variable=abActiveVolume]volume-a"
-      fi
-    displayName: "Adjust active volume for auto-rollback scenario"
+  # - bash: |
+  #     set -eu
+  #     if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
+  #       # auto-rollback will fail the first update (to volume-b) and
+  #       # the rollback should boot to volume-a
+  #       echo "##vso[task.setvariable variable=abActiveVolume]volume-a"
+  #     fi
+  #   displayName: "Adjust active volume for auto-rollback scenario"
 
   - template: ../testing_common/display-serial-logs.yml
     parameters:
@@ -240,14 +234,97 @@ steps:
       displayNameSpecifier: "A/B update into target OS B"
       artifactName: "junit_for_trident_ab_update_B"
 
+  # - bash: |
+  #     set -eu
+  #     if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
+  #       # for auto-rollback, only run the first update to test rollback
+  #       echo "##vso[task.setvariable variable=abActiveVolume]null"
+  #       echo "##vso[task.setvariable variable=skipJunitHandling]true"
+  #     fi
+  #   displayName: "Limit subsequent testing for auto-rollback scenario"
+
   - bash: |
-      set -eu
-      if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
-        # for auto-rollback, only run the first update to test rollback
-        echo "##vso[task.setvariable variable=abActiveVolume]null"
-        echo "##vso[task.setvariable variable=skipJunitHandling]true"
+      set -eux
+      # If there is a netlisten process, kill it so there is no port clash in the instance
+      if pgrep netlisten > /dev/null; then pkill netlisten; fi
+
+      NETLISTEN_CONFIG_ARGS=""
+      if [ -n "${{ parameters.netlistenConfigFile }}" ]; then
+        NETLISTEN_CONFIG_ARGS="--config ${{ parameters.netlistenConfigFile }}"
       fi
-    displayName: "Limit subsequent testing for auto-rollback scenario"
+
+      ./bin/netlisten --force-color $NETLISTEN_CONFIG_ARGS \
+          -m $(Build.SourcesDirectory)/trident-ab-update-metrics-target-os-A.jsonl \
+          --full-logstream ./logstream-full.log \
+          -s "${{ parameters.artifactsDirectory }}" \
+          -p ${{ parameters.netlistenPort }} > ./stage-finalize-ab-update-target-os-A.log 2>&1 &
+
+      PROXY_ARG=""
+      if [ -n "${{ parameters.httpsProxy }}" ]; then
+        PROXY_ARG="--proxy HTTPS_PROXY=${{ parameters.httpsProxy }}"
+      fi
+
+      # Create rollback copy of host config file
+      cp "${{ parameters.tridentConfigPath }}" "/tmp/trident-config-rollback.yaml"
+      # Add failing health checks to the rollback config
+      python3 ${{ parameters.tridentSourceDirectory }}/tests/e2e_tests/helpers/autorollback_host_config.py \
+          --hostconfig "/tmp/trident-config-rollback.yaml"
+
+      echo "Running script to stage and finalize A/B update..."
+      ./bin/storm-trident helper ab-update \
+          "${{ parameters.sshKeyPath }}" \
+          "${{ parameters.hostIp }}" \
+          "${{ parameters.userName }}" \
+          "${{ parameters.runtimeEnv }}" \
+          --trident-config "/tmp/trident-config-rollback.yaml" \
+          --version $(version) \
+          --stage-ab-update \
+          --finalize-ab-update \
+          --forced-rollback \
+          $PROXY_ARG
+
+      current_version=$(echo $(version))
+      new_version=$((current_version + 1))
+      # Un-set the 'x' flag to avoid errors.
+      set +x
+      echo "##vso[task.setvariable variable=version]$new_version"
+      echo "##vso[task.setvariable variable=abActiveVolume]volume-b"
+    timeoutInMinutes: 15
+    workingDirectory: $(Build.SourcesDirectory)
+    displayName: "🅰️🔄⎌ Stage and finalize A/B update into target OS A triggering auto-rollback"
+    condition: and(succeeded(), ne(variables['abActiveVolume'], 'null'))
+
+  - template: ../testing_common/display-serial-logs.yml
+    parameters:
+      netlistenConfigFile: ${{ parameters.netlistenConfigFile }}
+      outputDirectory: $(ob_outputDirectory)
+      partition: A
+      displayNameSuffix: "triggering auto-rollback"
+
+  - template: ../testing_common/display-deployment-logs.yml
+    parameters:
+      deploymentLogPath: $(Build.SourcesDirectory)/stage-finalize-ab-update-target-os-A.log
+      displayName: "📄 Display A/B update deployment logs for target OS A triggering auto-rollback"
+
+  - template: ../testing_common/display-deployment-logs.yml
+    parameters:
+      deploymentLogPath: $(Build.SourcesDirectory)/logstream-full.log
+      displayName: "📄 [TRACE] Display A/B update deployment logs for target OS A triggering auto-rollback"
+
+  - bash: |
+      set -eux
+      python3 -u -m pytest \
+          -m rollback \
+          --capture=no \
+          --junit-xml=${{ parameters.deploymentEnvironment }}_${{ parameters.runtimeEnv }}_${{ parameters.tridentConfigurationName }}_${{ parameters.jUnitXMLIdentifier }}_ab_update_A_$(System.JobAttempt).junit.xml \
+          --host ${{ parameters.hostIp }} \
+          --runtime-env ${{ parameters.runtimeEnv }} \
+          --configuration ${{ parameters.tridentConfigPath }} \
+          --ab-active-volume $(abActiveVolume)
+    timeoutInMinutes: 5
+    workingDirectory: $(Build.SourcesDirectory)/tests/e2e_tests
+    displayName: "🔬⎌ Run Trident E2E tests after A/B update into target OS A triggering auto-rollback"
+    condition: and(succeeded(), ne(variables['abActiveVolume'], 'null'))
 
   - bash: |
       set -eux
